# Bundles every recorded demo into app/demos_data.rb so the game needs no file reading.
#
#   ruby tools/bundle_demos.rb

dir = File.expand_path("../data/demos", __dir__)
entries = Dir[File.join(dir, "*.txt")].sort.map do |file|
  key = File.basename(file, ".txt")
  lines = File.readlines(file, chomp: true)
  demo_bike = lines.first.split.last.to_i
  runs = lines.drop(1).map { |l| l.split.map(&:to_i) }
  "  #{key.inspect} => { bike: #{demo_bike}, runs: #{runs.inspect} },"
end
File.write(File.expand_path("../app/demos_data.rb", __dir__),
           "# Generated by tools/bundle_demos.rb from data/demos/*.txt. Do not edit.\n" \
           "# Key \"<level>_<track>\"; runs are [throttle, lean, frames].\nDEMOS = {\n#{entries.join("\n")}\n}.freeze\n")
