# Converts data/levels.mrg (original big-endian level archive) into app/levels_data.rb,
# so the game never has to read binary files at runtime.
#
#   ruby tools/convert_levels.rb

class MrgReader
  def initialize(bytes)
    @bytes = bytes
    @pos = 0
  end

  attr_accessor :pos

  def int8
    v = @bytes.getbyte(@pos)
    @pos += 1
    v >= 128 ? v - 256 : v
  end

  def int16
    v = @bytes.byteslice(@pos, 2).unpack1("s>")
    @pos += 2
    v
  end

  def int32
    v = @bytes.byteslice(@pos, 4).unpack1("l>")
    @pos += 4
    v
  end
end

def read_index(r)
  Array.new(3) do
    Array.new(r.int32) do
      offset = r.int32
      name = +""
      40.times do
        c = r.int8
        break if c == 0
        name << c.chr
      end
      { name: name.tr("_", " "), offset: offset }
    end
  end
end

# Raw values straight from the file; GameLevel applies the original int32 math on load.
def read_level(r, offset)
  r.pos = offset
  r.pos += 20 if r.int8 == 50
  start_x, start_y, finish_x, finish_y = r.int32, r.int32, r.int32, r.int32
  count = r.int16
  points = [[r.int32, r.int32]]
  (count - 1).times do
    mode = r.int8
    points << (mode == -1 ? [:abs, r.int32, r.int32] : [mode, r.int8])
  end
  { start: [start_x, start_y], finish: [finish_x, finish_y], points: points }
end

root = File.expand_path("..", __dir__)
reader = MrgReader.new(File.binread(File.join(root, "data/levels.mrg")))
leagues = read_index(reader).map do |tracks|
  tracks.map { |t| read_level(reader, t[:offset]).merge(name: t[:name]) }
end

out = +"# Generated by tools/convert_levels.rb from data/levels.mrg. Do not edit.\n"
out << "# points: [x, y] first point, then [dx, dy] deltas or [:abs, x, y] resets.\n"
out << "LEVELS = [\n"
leagues.each do |tracks|
  out << "  [\n"
  tracks.each do |t|
    out << "    { name: #{t[:name].inspect}, start: #{t[:start].inspect}, finish: #{t[:finish].inspect},\n"
    out << "      points: #{t[:points].inspect} },\n"
  end
  out << "  ],\n"
end
out << "]\n"

File.write(File.join(root, "app/levels_data.rb"), out)
puts leagues.map { |ts| "#{ts.size} tracks: #{ts.map { |t| t[:name] }.join(', ')}" }
